# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dianfeijiegou.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(509, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(24)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 1, item)
        self.horizontalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "峰值类型"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "电费价格（元/度）"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "谷\n"
""))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "谷"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "谷"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "谷"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form", "谷"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form", "谷"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Form", "谷"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Form", "平"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Form", "峰"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Form", "峰"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("Form", "峰"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("Form", "平"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("Form", "平"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("Form", "平"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("Form", "平"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("Form", "峰"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.item(16, 1)
        item.setText(_translate("Form", "峰"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.item(17, 1)
        item.setText(_translate("Form", "峰"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.item(18, 1)
        item.setText(_translate("Form", "峰"))
        item = self.tableWidget.item(19, 0)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.item(19, 1)
        item.setText(_translate("Form", "尖"))
        item = self.tableWidget.item(20, 0)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.item(20, 1)
        item.setText(_translate("Form", "尖"))
        item = self.tableWidget.item(21, 0)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget.item(21, 1)
        item.setText(_translate("Form", "尖"))
        item = self.tableWidget.item(22, 0)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget.item(22, 1)
        item.setText(_translate("Form", "平"))
        item = self.tableWidget.item(23, 0)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget.item(23, 1)
        item.setText(_translate("Form", "谷"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

if __name__=="__main__":
    import sys
    app=QtWidgets.QApplication(sys.argv)
    # widget=QtWidgets.QWidget()
    ui=Ui_Form()
    ui.setupUi(ui)
    ui.show()
    sys.exit(app.exec_())
    
# 这个思路可能不对， 我去搜资料了。你也去搜资料。 不要再随便动代码。没有意义