"""roles_add_height

Revision ID: 8619d083180e
Revises: d976bd08435d
Create Date: 2018-04-14 11:26:32.008169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8619d083180e'
down_revision = 'd976bd08435d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'height')
    # ### end Alembic commands ###
