"""roles_add_title

Revision ID: d976bd08435d
Revises: fdc8fb218f90
Create Date: 2018-04-14 11:24:44.587237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd976bd08435d'
down_revision = 'fdc8fb218f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'title')
    # ### end Alembic commands ###
